/** Whisper-supported languages for the language selector dropdown. */
export const LANGUAGES: { code: string; name: string; native: string }[] = [
  { code: "auto", name: "Автоопределение", native: "Auto" },
  { code: "af",   name: "Африкаанс",       native: "Afrikaans" },
  { code: "sq",   name: "Албанский",       native: "Shqip" },
  { code: "am",   name: "Амхарский",       native: "አማርኛ" },
  { code: "ar",   name: "Арабский",        native: "العربية" },
  { code: "hy",   name: "Армянский",       native: "Հայերեն" },
  { code: "az",   name: "Азербайджанский", native: "Azərbaycan" },
  { code: "eu",   name: "Баскский",        native: "Euskara" },
  { code: "be",   name: "Белорусский",     native: "Беларуская" },
  { code: "bn",   name: "Бенгальский",     native: "বাংলা" },
  { code: "bs",   name: "Боснийский",      native: "Bosanski" },
  { code: "bg",   name: "Болгарский",      native: "Български" },
  { code: "ca",   name: "Каталанский",     native: "Català" },
  { code: "zh",   name: "Китайский",       native: "中文" },
  { code: "hr",   name: "Хорватский",      native: "Hrvatski" },
  { code: "cs",   name: "Чешский",         native: "Čeština" },
  { code: "da",   name: "Датский",         native: "Dansk" },
  { code: "nl",   name: "Нидерландский",   native: "Nederlands" },
  { code: "en",   name: "Английский",      native: "English" },
  { code: "et",   name: "Эстонский",       native: "Eesti" },
  { code: "fi",   name: "Финский",         native: "Suomi" },
  { code: "fr",   name: "Французский",     native: "Français" },
  { code: "gl",   name: "Галисийский",     native: "Galego" },
  { code: "ka",   name: "Грузинский",      native: "ქართული" },
  { code: "de",   name: "Немецкий",        native: "Deutsch" },
  { code: "el",   name: "Греческий",       native: "Ελληνικά" },
  { code: "gu",   name: "Гуджарати",       native: "ગુજરાતી" },
  { code: "ht",   name: "Гаитянский креольский", native: "Kreyòl ayisyen" },
  { code: "he",   name: "Иврит",           native: "עברית" },
  { code: "hi",   name: "Хинди",           native: "हिन्दी" },
  { code: "hu",   name: "Венгерский",      native: "Magyar" },
  { code: "is",   name: "Исландский",      native: "Íslenska" },
  { code: "id",   name: "Индонезийский",   native: "Bahasa Indonesia" },
  { code: "ga",   name: "Ирландский",      native: "Gaeilge" },
  { code: "it",   name: "Итальянский",     native: "Italiano" },
  { code: "ja",   name: "Японский",        native: "日本語" },
  { code: "kn",   name: "Каннада",         native: "ಕನ್ನಡ" },
  { code: "kk",   name: "Казахский",       native: "Қазақша" },
  { code: "km",   name: "Кхмерский",       native: "ខ្មែរ" },
  { code: "ko",   name: "Корейский",       native: "한국어" },
  { code: "ky",   name: "Кыргызский",      native: "Кыргызча" },
  { code: "lo",   name: "Лаосский",        native: "ລາວ" },
  { code: "lv",   name: "Латвийский",      native: "Latviešu" },
  { code: "lt",   name: "Литовский",       native: "Lietuvių" },
  { code: "mk",   name: "Македонский",     native: "Македонски" },
  { code: "ms",   name: "Малайский",       native: "Bahasa Melayu" },
  { code: "ml",   name: "Малаялам",        native: "മലയാളം" },
  { code: "mt",   name: "Мальтийский",     native: "Malti" },
  { code: "mi",   name: "Маори",           native: "Te Reo Māori" },
  { code: "mn",   name: "Монгольский",     native: "Монгол" },
  { code: "ne",   name: "Непальский",      native: "नेपाली" },
  { code: "nb",   name: "Норвежский",      native: "Norsk" },
  { code: "ps",   name: "Пушту",           native: "پښتو" },
  { code: "fa",   name: "Персидский",      native: "فارسی" },
  { code: "pl",   name: "Польский",        native: "Polski" },
  { code: "pt",   name: "Португальский",   native: "Português" },
  { code: "pa",   name: "Панджаби",        native: "ਪੰਜਾਬੀ" },
  { code: "ro",   name: "Румынский",       native: "Română" },
  { code: "ru",   name: "Русский",         native: "Русский" },
  { code: "sr",   name: "Сербский",        native: "Српски" },
  { code: "si",   name: "Сингальский",     native: "සිංහල" },
  { code: "sk",   name: "Словацкий",       native: "Slovenčina" },
  { code: "sl",   name: "Словенский",      native: "Slovenščina" },
  { code: "so",   name: "Сомалийский",     native: "Soomaali" },
  { code: "es",   name: "Испанский",       native: "Español" },
  { code: "sw",   name: "Суахили",         native: "Kiswahili" },
  { code: "sv",   name: "Шведский",        native: "Svenska" },
  { code: "tg",   name: "Таджикский",      native: "Тоҷикӣ" },
  { code: "ta",   name: "Тамильский",      native: "தமிழ்" },
  { code: "te",   name: "Телугу",          native: "తెలుగు" },
  { code: "th",   name: "Тайский",         native: "ภาษาไทย" },
  { code: "tr",   name: "Турецкий",        native: "Türkçe" },
  { code: "uk",   name: "Украинский",      native: "Українська" },
  { code: "ur",   name: "Урду",            native: "اردو" },
  { code: "uz",   name: "Узбекский",       native: "O'zbek" },
  { code: "vi",   name: "Вьетнамский",     native: "Tiếng Việt" },
  { code: "cy",   name: "Валлийский",      native: "Cymraeg" },
  { code: "xh",   name: "Коса",            native: "isiXhosa" },
  { code: "yi",   name: "Идиш",            native: "ייִדיש" },
  { code: "yo",   name: "Йоруба",          native: "Yorùbá" },
  { code: "zu",   name: "Зулу",            native: "isiZulu" },
];
